#baseURL = "https://docs.tugboat.qa/"
languageCode = "en-us"
title = "Tugboat Documentation"
#googleAnalytics = "UA-69911960-4"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

  # Change default color scheme with a variant one. Can be "red", "blue", "green".

  themeVariant = "blue"

  # Set this to true to disable copy-to-clipboard button for inline code.

  disableInlineCopyToClipBoard = true
