services:
  apache:
    image: tugboatqa/httpd
    commands:
      init:
        - apt-get update
        - apt-get install -y apt-transport-https
        - apt-get install hugo
      build:
        - git submodule init
        - git submodule update
        - hugo
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"
